from __future__ import annotations

import argparse
import hashlib
import json
import statistics
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable, Literal

from pydantic import BaseModel, ConfigDict

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from src.io_utils import read_jsonl
from src.v3.build_corpus import file_sha256
from src.v3.collect_details import _canonical_json_bytes, _serialize_jsonl, write_immutable
from src.v3.evaluate_semantic_requirement_planner import (
    call_structured,
    runtime_metadata,
)


EVALUATOR_VERSION = "exact-extractive-answer-assembler-pilot-v3.1"
PROPOSAL_SCHEMA_VERSION = "exact-extractive-span-proposal-v3.0"
CASE_SCHEMA_VERSION = "exact-extractive-assembler-case-v3.0"
REPORT_SCHEMA_VERSION = "exact-extractive-assembler-report-v3.1"
MANIFEST_SCHEMA_VERSION = "exact-extractive-assembler-manifest-v3.1"
DEFAULT_MODEL = "qwen3:8b"

DEFAULT_ENUMERATION = Path(
    "data/v3/evaluation/semantic_requirement_enumeration_"
    "495caba182115c2dbec6e846dca7c0809c4cb8a4de552ee1268440d254d2ba9c.jsonl"
)
DEFAULT_CANARY = Path(
    "data/v3/evaluation/early_generalization_authored_canary_"
    "28b0aa6c06add6ae0b81a7888d0f0c71bc46450058f6cedcb1588a5cdd83b85d.jsonl"
)
DEFAULT_DEV = Path(
    "data/v3/evaluation/retrieval_dev_v3.1_"
    "b98d62e1e3920f9e4a58bd602aa6cda1036827d1122f51d3478a95aa8d1a2978.jsonl"
)
DEFAULT_RERANK_RESULTS = Path(
    "data/v3/evidence/requirement_reranker_ab_results_"
    "db7dbd2281687c07aebf88dc43a07bd90cf280e690188c06a79cf9e3a2b04913.jsonl"
)
DEFAULT_RERANK_SCORES = Path(
    "data/v3/evidence/requirement_reranker_scores_"
    "fcecc605fec6c23a03c1aafa66f6a7796c9750f9091d10706485cc4899518e53.jsonl"
)
DEFAULT_RERANK_MANIFEST = Path(
    "data/v3/evidence/requirement_reranker_manifest_"
    "9d55090789cee5baebc026fc735658896807db73ef2076bcb3bbce61f67a70e4.json"
)
DEFAULT_DEV_BASELINE_CASES = Path(
    "data/v3/runtime/unified_runtime_cases_"
    "f28e2fbfb768c901dc4f1079f262252d645a74c7e4ee494180c2879e528f7789.jsonl"
)
DEFAULT_DEV_BASELINE_MANIFEST = Path(
    "data/v3/runtime/unified_runtime_manifest_"
    "7f9d747c65960db5985c2ddf07592e09f0f82053b41db2801ce117151ac032c3.json"
)
DEFAULT_CANARY_BASELINE_CASES = Path(
    "data/v3/evaluation/authored_canary_first_run_cases_"
    "a326d9fd96a4cfcaf9b2d38d74f27fffe26b62dfc1364063c8258891546beecd.jsonl"
)
DEFAULT_CANARY_BASELINE_MANIFEST = Path(
    "data/v3/evaluation/authored_canary_first_run_manifest_"
    "4a2aef81660a13b113ab63a3739126afcddcb6b0b60f2af740becf3bfbdd93dd.json"
)
DEFAULT_CHUNKS = Path(
    "data/v3/chunks/chunks_dnf_official_v3.1_"
    "bd0242b3f19646c22eafd2e61bf2544e670718a1c9927de288decb5657e92885.jsonl"
)
DEFAULT_CONTRACT = Path("docs/v3/extractive_answer_assembler_pilot.md")


SPAN_SYSTEM_PROMPT = """You are an exact extractive span locator.
For each frozen atomic requirement, inspect only its provided evidence chunks.
If one chunk directly states the requested answer, return status=supported,
that exact chunk_id, and ONE shortest useful continuous substring copied
verbatim from that chunk. Include enough nearby label or condition to make the
value understandable. Never paraphrase, translate, join separate passages,
insert ellipses, normalize whitespace, or answer in your own words.

If none of the provided chunks directly states the answer, return
status=unsupported with empty strings for cited_chunk_id and proposed_span.
The caller normalizes those empty strings to null. Preserve every
requirement_index exactly and return no explanation or answer prose. The caller
will reject every proposed span that is not an exact substring."""


class SpanProposal(BaseModel):
    model_config = ConfigDict(extra="forbid")

    requirement_index: int
    status: Literal["supported", "unsupported"]
    # Ollama 0.32.1 cannot compile the nullable-string grammar generated by
    # Pydantic here. Empty strings are a transport-only sentinel and are
    # normalized back to null before freezing the proposal artifact.
    cited_chunk_id: str
    proposed_span: str


class SpanProposalOutput(BaseModel):
    model_config = ConfigDict(extra="forbid")

    decisions: list[SpanProposal]


def _sha256_bytes(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def _relative(root: Path, path: Path) -> str:
    return path.resolve().relative_to(root.resolve()).as_posix()


def _git_head(root: Path) -> str:
    return subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=root,
        check=True,
        capture_output=True,
        text=True,
    ).stdout.strip()


def _prompt_sha256() -> str:
    return _sha256_bytes(SPAN_SYSTEM_PROMPT.encode("utf-8"))


def _baseline_canary_groups(row: dict[str, Any]) -> set[str]:
    return {
        group["group_id"]
        for group in row.get("group_results", [])
        if group.get("baseline_cited_hit")
    }


def build_cases(
    canary_gold: list[dict[str, Any]],
    dev_gold: list[dict[str, Any]],
    enumeration_rows: list[dict[str, Any]],
    rerank_results: list[dict[str, Any]],
    rerank_scores: list[dict[str, Any]],
    canary_baseline: list[dict[str, Any]],
    dev_baseline: list[dict[str, Any]],
    chunks: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    enumeration_by_id = {row["case_id"]: row for row in enumeration_rows}
    results_by_id = {row["case_id"]: row for row in rerank_results}
    scores_by_id = {row["case_id"]: row for row in rerank_scores}
    chunks_by_id = {row["chunk_id"]: row for row in chunks}
    if any(
        len(mapping) != 95
        for mapping in (enumeration_by_id, results_by_id, scores_by_id)
    ):
        raise RuntimeError("Clean enumeration and reranker inputs must contain 95 IDs")

    output = []
    for dataset, gold_rows, baseline_rows in (
        ("downgraded_canary_32", canary_gold, canary_baseline),
        ("adaptive_dev_63", dev_gold, dev_baseline),
    ):
        baseline_by_id = {row["case_id"]: row for row in baseline_rows}
        gold_ids = {row["dev_id"] for row in gold_rows}
        if set(baseline_by_id) != gold_ids:
            raise RuntimeError(f"Baseline IDs differ from {dataset} gold IDs")
        for gold in gold_rows:
            case_id = gold["dev_id"]
            result = results_by_id[case_id]
            score_row = scores_by_id[case_id]
            selected_ids = result["baseline"]["selected_chunk_ids"]
            unknown = set(selected_ids) - set(chunks_by_id)
            if unknown:
                raise RuntimeError(f"Unknown selected chunks: {sorted(unknown)}")
            selected_order = {chunk_id: index for index, chunk_id in enumerate(selected_ids)}
            requirement_attribution = []
            for requirement in score_row["requirements"]:
                selected_scores = [
                    candidate
                    for candidate in requirement["candidates"]
                    if candidate["chunk_id"] in selected_order
                ]
                selected_scores.sort(
                    key=lambda candidate: (
                        -float(candidate["reranker_score"]),
                        selected_order[candidate["chunk_id"]],
                        candidate["chunk_id"],
                    )
                )
                requirement_attribution.append(
                    {
                        "requirement_index": requirement["requirement_index"],
                        "requirement_id": requirement["requirement_id"],
                        "ordered_chunk_ids": [
                            candidate["chunk_id"] for candidate in selected_scores
                        ],
                    }
                )
            baseline = baseline_by_id[case_id]
            baseline_group_ids = (
                _baseline_canary_groups(baseline)
                if dataset == "downgraded_canary_32"
                else set(baseline.get("cited_evidence_group_ids", []))
            )
            output.append(
                {
                    "case_id": case_id,
                    "dataset": dataset,
                    "question": gold["question"],
                    "source_ids": sorted(set(gold.get("source_ids", []))),
                    "gold_answerability": gold.get("answerability"),
                    "requirements": enumeration_by_id[case_id]["requirements"],
                    "evidence_groups": gold.get("evidence_groups", []),
                    "selected_chunk_ids": selected_ids,
                    "selected_chunks": {
                        chunk_id: chunks_by_id[chunk_id]["display_text"]
                        for chunk_id in selected_ids
                    },
                    "requirement_attribution": requirement_attribution,
                    "baseline_cited_group_ids": sorted(baseline_group_ids),
                    "retrieval_bound_group_ids": result["retrieval_bound_group_ids"],
                }
            )
    if len(output) != 95 or {
        row["case_id"] for row in output
    } != set(enumeration_by_id):
        raise RuntimeError("Assembler requires the exact frozen 32+63 population")
    return sorted(output, key=lambda row: row["case_id"])


def model_prompt(case: dict[str, Any]) -> str:
    attribution_by_index = {
        row["requirement_index"]: row for row in case["requirement_attribution"]
    }
    payload = {
        "question": case["question"],
        "requirements": [
            {
                "requirement_index": index,
                "subject": requirement["subject"],
                "relation": requirement["relation"],
                "value_type": requirement["value_type"],
                "subject_group": requirement["subject_group"],
                "candidate_chunk_ids_in_relevance_order": attribution_by_index[
                    index
                ]["ordered_chunk_ids"],
            }
            for index, requirement in enumerate(case["requirements"], 1)
        ],
        "evidence_chunks": [
            {"chunk_id": chunk_id, "text": case["selected_chunks"][chunk_id]}
            for chunk_id in case["selected_chunk_ids"]
        ],
        "expected_decision_count": len(case["requirements"]),
    }
    return "Locate exact answer spans for this case:\n" + json.dumps(
        payload, ensure_ascii=False, sort_keys=True
    )


def run_span_model(
    cases: list[dict[str, Any]],
    *,
    model: str,
    timeout: float,
    caller: Callable[..., tuple[BaseModel, dict[str, Any]]] = call_structured,
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    proposals = []
    call_logs = []
    callable_cases = [row for row in cases if row["evidence_groups"]]
    for ordinal, case in enumerate(callable_cases, 1):
        parsed, log = caller(
            model=model,
            system_prompt=SPAN_SYSTEM_PROMPT,
            user_prompt=model_prompt(case),
            output_type=SpanProposalOutput,
            timeout=timeout,
        )
        decisions = [decision.model_dump() for decision in parsed.decisions]
        for decision in decisions:
            if decision["status"] == "unsupported":
                decision["cited_chunk_id"] = None
                decision["proposed_span"] = None
        expected = set(range(1, len(case["requirements"]) + 1))
        by_index: dict[int, list[dict[str, Any]]] = {}
        for decision in decisions:
            by_index.setdefault(decision["requirement_index"], []).append(decision)
        missing = sorted(expected - set(by_index))
        duplicate = sorted(
            index for index, values in by_index.items() if index in expected and len(values) > 1
        )
        unexpected = sorted(set(by_index) - expected)
        normalized = []
        for index in sorted(expected):
            if index in missing or index in duplicate:
                normalized.append(
                    {
                        "requirement_index": index,
                        "status": "supported",
                        "cited_chunk_id": "",
                        "proposed_span": "",
                        "model_output_error": "missing_decision"
                        if index in missing
                        else "duplicate_decision",
                    }
                )
            else:
                normalized.append(by_index[index][0])
        model_output_errors = {
            "missing_requirement_indices": missing,
            "duplicate_requirement_indices": duplicate,
            "unexpected_requirement_indices": unexpected,
        }
        proposals.append(
            {
                "proposal_schema_version": PROPOSAL_SCHEMA_VERSION,
                "case_id": case["case_id"],
                "decisions": normalized,
                "model_output_errors": model_output_errors,
            }
        )
        call_logs.append({"case_id": case["case_id"], **log})
        if ordinal % 10 == 0 or ordinal == len(callable_cases):
            print(
                f"span cases {ordinal}/{len(callable_cases)}",
                file=sys.stderr,
                flush=True,
            )
    proposal_ids = {row["case_id"] for row in proposals}
    for case in cases:
        if case["case_id"] not in proposal_ids:
            proposals.append(
                {
                    "proposal_schema_version": PROPOSAL_SCHEMA_VERSION,
                    "case_id": case["case_id"],
                    "decisions": [
                        {
                            "requirement_index": index,
                            "status": "unsupported",
                            "cited_chunk_id": None,
                            "proposed_span": None,
                        }
                        for index in range(1, len(case["requirements"]) + 1)
                    ],
                    "not_evaluated_no_gold_evidence_groups": True,
                }
            )
    return sorted(proposals, key=lambda row: row["case_id"]), call_logs


def cut_exact_spans(
    cases: list[dict[str, Any]], proposals: list[dict[str, Any]]
) -> list[dict[str, Any]]:
    proposals_by_id = {row["case_id"]: row for row in proposals}
    output = []
    for case in cases:
        proposal = proposals_by_id[case["case_id"]]
        decisions = []
        for requirement, raw in zip(
            case["requirements"], proposal["decisions"], strict=True
        ):
            if raw.get("model_output_error"):
                decisions.append(
                    {
                        "requirement_id": requirement["requirement_id"],
                        "status": "invalid_model_output",
                        "extracted_span": None,
                        "cited_chunk_id": None,
                        "start_char": None,
                        "end_char": None,
                        "unsupported_message": "문서에서 확인 불가",
                        "proposed_span": None,
                        "model_output_error": raw["model_output_error"],
                    }
                )
                continue
            if raw["status"] == "unsupported":
                decisions.append(
                    {
                        "requirement_id": requirement["requirement_id"],
                        "status": "unsupported",
                        "extracted_span": None,
                        "cited_chunk_id": None,
                        "start_char": None,
                        "end_char": None,
                        "unsupported_message": "문서에서 확인 불가",
                        "proposed_span": raw.get("proposed_span"),
                    }
                )
                continue
            chunk_id = raw.get("cited_chunk_id")
            proposed = raw.get("proposed_span")
            if chunk_id not in case["selected_chunks"]:
                status = "invalid_chunk"
                start = None
            elif not isinstance(proposed, str) or not proposed:
                status = "invalid_empty_span"
                start = None
            else:
                start = case["selected_chunks"][chunk_id].find(proposed)
                status = "supported_exact" if start >= 0 else "invalid_non_substring"
            if status == "supported_exact":
                end = start + len(proposed)
                extracted = case["selected_chunks"][chunk_id][start:end]
            else:
                end = None
                extracted = None
            decisions.append(
                {
                    "requirement_id": requirement["requirement_id"],
                    "status": status,
                    "extracted_span": extracted,
                    "cited_chunk_id": chunk_id,
                    "start_char": start if status == "supported_exact" else None,
                    "end_char": end,
                    "unsupported_message": "문서에서 확인 불가"
                    if status != "supported_exact"
                    else None,
                    "proposed_span": proposed,
                }
            )
        output.append(
            {
                "case_schema_version": CASE_SCHEMA_VERSION,
                "case_id": case["case_id"],
                "dataset": case["dataset"],
                "decisions": decisions,
                "model_output_errors": proposal.get("model_output_errors", {}),
            }
        )
    return sorted(output, key=lambda row: row["case_id"])


def _normalize_ws(value: str) -> str:
    return " ".join(value.split())


def score_cases(
    cases: list[dict[str, Any]], assembled_rows: list[dict[str, Any]]
) -> list[dict[str, Any]]:
    assembled_by_id = {row["case_id"]: row for row in assembled_rows}
    output = []
    for case in cases:
        assembled = assembled_by_id[case["case_id"]]
        valid_decisions = [
            decision
            for decision in assembled["decisions"]
            if decision["status"] == "supported_exact"
        ]
        selected_ids = set(case["selected_chunk_ids"])
        groups = []
        retrieval_bound_ids = set(case["retrieval_bound_group_ids"])
        for group in case["evidence_groups"]:
            acceptable = set(group["acceptable_chunk_ids"])
            selected_bound = bool(selected_ids & acceptable)
            retrieval_bound = group["group_id"] in retrieval_bound_ids
            matching = [
                decision
                for decision in valid_decisions
                if decision["cited_chunk_id"] in acceptable
            ]
            gold_span = _normalize_ws(str(group.get("evidence_span", "")))
            gold_span_aligned = any(
                _normalize_ws(decision["extracted_span"]) in gold_span
                or gold_span in _normalize_ws(decision["extracted_span"])
                for decision in matching
                if gold_span and decision["extracted_span"]
            )
            groups.append(
                {
                    "group_id": group["group_id"],
                    "selected_bound": selected_bound,
                    "retrieval_bound": retrieval_bound,
                    "selection_bound": not retrieval_bound and not selected_bound,
                    "baseline_cited": group["group_id"]
                    in case["baseline_cited_group_ids"],
                    "assembler_cited": bool(matching),
                    "gold_span_containment_match": gold_span_aligned,
                }
            )
        bound_groups = [group for group in groups if group["selected_bound"]]
        gate_eligible = bool(groups) and len(bound_groups) == len(groups)
        acceptable_ids = {
            chunk_id
            for group in case["evidence_groups"]
            for chunk_id in group["acceptable_chunk_ids"]
        }
        valid_gold_citations = [
            decision
            for decision in valid_decisions
            if decision["cited_chunk_id"] in acceptable_ids
        ]
        if bound_groups and any(not group["assembler_cited"] for group in bound_groups):
            if any(
                decision["status"].startswith("invalid_")
                for decision in assembled["decisions"]
            ):
                extraction_failure_type = "invalid_span"
            elif not valid_decisions:
                extraction_failure_type = "model_unsupported"
            else:
                extraction_failure_type = "valid_span_wrong_chunk_or_incomplete_groups"
        else:
            extraction_failure_type = None
        output.append(
            {
                "case_id": case["case_id"],
                "dataset": case["dataset"],
                "source_ids": case["source_ids"],
                "requirement_count": len(case["requirements"]),
                "valid_exact_requirement_count": len(valid_decisions),
                "valid_gold_chunk_requirement_count": len(valid_gold_citations),
                "unsupported_requirement_count": sum(
                    decision["status"] == "unsupported"
                    for decision in assembled["decisions"]
                ),
                "invalid_requirement_count": sum(
                    decision["status"].startswith("invalid_")
                    for decision in assembled["decisions"]
                ),
                "model_output_error": any(
                    assembled.get("model_output_errors", {}).values()
                ),
                "all_planner_requirements_cited": len(valid_gold_citations)
                == len(case["requirements"]),
                "groups": groups,
                "gate_eligible": gate_eligible,
                "all_groups_baseline_cited": all(
                    group["baseline_cited"] for group in groups
                )
                if gate_eligible
                else None,
                "all_groups_assembler_cited": all(
                    group["assembler_cited"] for group in groups
                )
                if gate_eligible
                else None,
                "upstream_unselected_group_count": len(groups) - len(bound_groups),
                "extraction_failure_type": extraction_failure_type,
            }
        )
    return sorted(output, key=lambda row: row["case_id"])


def aggregate(rows: list[dict[str, Any]]) -> dict[str, Any]:
    evidence_rows = [row for row in rows if row["groups"]]
    eligible_rows = [row for row in evidence_rows if row["gate_eligible"]]
    bound_groups = [
        group
        for row in evidence_rows
        for group in row["groups"]
        if group["selected_bound"]
    ]
    all_groups = [group for row in evidence_rows for group in row["groups"]]
    retrieval_bound_groups = [group for group in all_groups if group["retrieval_bound"]]
    selection_bound_groups = [group for group in all_groups if group["selection_bound"]]
    baseline_hits = sum(group["baseline_cited"] for group in bound_groups)
    assembler_hits = sum(group["assembler_cited"] for group in bound_groups)
    baseline_questions = sum(row["all_groups_baseline_cited"] for row in eligible_rows)
    assembler_questions = sum(row["all_groups_assembler_cited"] for row in eligible_rows)
    improvements = sum(
        not group["baseline_cited"] and group["assembler_cited"]
        for group in bound_groups
    )
    regressions = sum(
        group["baseline_cited"] and not group["assembler_cited"]
        for group in bound_groups
    )
    question_improvements = sum(
        not row["all_groups_baseline_cited"] and row["all_groups_assembler_cited"]
        for row in eligible_rows
    )
    question_regressions = sum(
        row["all_groups_baseline_cited"] and not row["all_groups_assembler_cited"]
        for row in eligible_rows
    )
    requirement_total = sum(row["requirement_count"] for row in evidence_rows)
    valid_exact_total = sum(row["valid_exact_requirement_count"] for row in evidence_rows)
    valid_gold_total = sum(
        row["valid_gold_chunk_requirement_count"] for row in evidence_rows
    )
    invalid_total = sum(row["invalid_requirement_count"] for row in evidence_rows)
    proposed_supported_total = valid_exact_total + invalid_total
    failure_types: dict[str, int] = {}
    for row in evidence_rows:
        failure = row["extraction_failure_type"]
        if failure:
            failure_types[failure] = failure_types.get(failure, 0) + 1
    return {
        "row_count": len(rows),
        "evidence_bearing_question_count": len(evidence_rows),
        "gate_eligible_question_count": len(eligible_rows),
        "upstream_bound_question_count": len(evidence_rows) - len(eligible_rows),
        "upstream_unselected_evidence_group_count": sum(
            row["upstream_unselected_group_count"] for row in evidence_rows
        ),
        "candidate_selected_evidence_group_count": len(bound_groups),
        "all_human_gold_evidence_group_count": len(all_groups),
        "baseline_evidence_group_citation": {
            "successes": baseline_hits,
            "total": len(bound_groups),
            "rate": round(baseline_hits / len(bound_groups), 6)
            if bound_groups
            else None,
        },
        "assembler_evidence_group_citation": {
            "successes": assembler_hits,
            "total": len(bound_groups),
            "rate": round(assembler_hits / len(bound_groups), 6)
            if bound_groups
            else None,
        },
        "all_human_gold_baseline_evidence_group_citation": {
            "successes": sum(group["baseline_cited"] for group in all_groups),
            "total": len(all_groups),
        },
        "all_human_gold_assembler_evidence_group_citation": {
            "successes": sum(group["assembler_cited"] for group in all_groups),
            "total": len(all_groups),
        },
        "baseline_all_groups_cited_questions": {
            "successes": baseline_questions,
            "total": len(eligible_rows),
            "rate": round(baseline_questions / len(eligible_rows), 6)
            if eligible_rows
            else None,
        },
        "assembler_all_groups_cited_questions": {
            "successes": assembler_questions,
            "total": len(eligible_rows),
            "rate": round(assembler_questions / len(eligible_rows), 6)
            if eligible_rows
            else None,
        },
        "per_requirement_exact_span_coverage": {
            "successes": valid_exact_total,
            "total": requirement_total,
            "rate": round(valid_exact_total / requirement_total, 6)
            if requirement_total
            else None,
        },
        "per_requirement_gold_chunk_citation": {
            "successes": valid_gold_total,
            "total": requirement_total,
            "rate": round(valid_gold_total / requirement_total, 6)
            if requirement_total
            else None,
        },
        "all_planner_requirements_cited_questions": {
            "successes": sum(row["all_planner_requirements_cited"] for row in eligible_rows),
            "total": len(eligible_rows),
        },
        "span_validity": {
            "valid_exact": valid_exact_total,
            "proposed_supported": proposed_supported_total,
            "invalid": invalid_total,
            "rate": round(valid_exact_total / proposed_supported_total, 6)
            if proposed_supported_total
            else None,
        },
        "model_output_error_question_count": sum(
            row["model_output_error"] for row in evidence_rows
        ),
        "comparison": {
            "evidence_group_improvement_count": improvements,
            "evidence_group_regression_count": regressions,
            "all_groups_question_improvement_count": question_improvements,
            "all_groups_question_regression_count": question_regressions,
        },
        "unsupported": {
            "upstream_bound_question_count": len(evidence_rows) - len(eligible_rows),
            "retrieval_bound_question_count": sum(
                any(group["retrieval_bound"] for group in row["groups"])
                for row in evidence_rows
            ),
            "retrieval_bound_evidence_group_count": len(retrieval_bound_groups),
            "selection_bound_question_count": sum(
                any(group["selection_bound"] for group in row["groups"])
                for row in evidence_rows
            ),
            "selection_bound_evidence_group_count": len(selection_bound_groups),
            "assembler_failure_question_count": sum(
                bool(row["extraction_failure_type"]) for row in eligible_rows
            ),
            "failure_type_counts": dict(sorted(failure_types.items())),
            "unsupported_requirement_count": sum(
                row["unsupported_requirement_count"] for row in evidence_rows
            ),
        },
        "gold_span_containment_match_count": sum(
            group["gold_span_containment_match"] for group in bound_groups
        ),
    }


def gate(metrics: dict[str, Any]) -> dict[str, Any]:
    combined = metrics["combined"]
    dev = metrics["adaptive_dev_63"]
    checks = {
        "dev_evidence_group_hits_improve_over_47": dev[
            "assembler_evidence_group_citation"
        ]["successes"]
        > 47,
        "combined_all_groups_questions_improve": combined[
            "assembler_all_groups_cited_questions"
        ]["successes"]
        > combined["baseline_all_groups_cited_questions"]["successes"],
        "strict_evidence_group_regression_zero": combined["comparison"][
            "evidence_group_regression_count"
        ]
        == 0,
        "strict_question_regression_zero": combined["comparison"][
            "all_groups_question_regression_count"
        ]
        == 0,
        "invalid_non_substring_zero": combined["span_validity"]["invalid"] == 0,
        "model_output_error_zero": combined["model_output_error_question_count"]
        == 0,
    }
    return {
        "checks": checks,
        "pass": all(checks.values()),
        "decision": "GO_EXTRACTIVE_REQUIREMENT_CITATION"
        if all(checks.values())
        else "NO_GO_CAUSE_ANALYSIS",
    }


def _latency(logs: list[dict[str, Any]]) -> dict[str, Any]:
    values = sorted(float(row["latency_ms"]) for row in logs)
    return {
        "question_call_count": len(values),
        "median_ms": round(statistics.median(values), 3) if values else None,
        "p95_ms": values[min(len(values) - 1, int(len(values) * 0.95))]
        if values
        else None,
        "total_ms": round(sum(values), 3),
        "prompt_tokens": sum(int(row.get("prompt_tokens", 0)) for row in logs),
        "completion_tokens": sum(
            int(row.get("completion_tokens", 0)) for row in logs
        ),
    }


def _markdown(report: dict[str, Any]) -> bytes:
    combined = report["metrics"]["combined"]
    dev = report["metrics"]["adaptive_dev_63"]
    lines = [
        "# Exact-extractive Answer Assembler pilot",
        "",
        f"- Decision: **{report['decision']}**",
        f"- Dev direct group comparison: 47/59 baseline -> {dev['all_human_gold_assembler_evidence_group_citation']['successes']}/59 assembler",
        f"- Dev selected-input subset: {dev['assembler_evidence_group_citation']['successes']}/{dev['assembler_evidence_group_citation']['total']}",
        f"- Combined all-groups questions: {combined['baseline_all_groups_cited_questions']['successes']}/{combined['baseline_all_groups_cited_questions']['total']} -> {combined['assembler_all_groups_cited_questions']['successes']}/{combined['assembler_all_groups_cited_questions']['total']}",
        f"- Span validity: {combined['span_validity']['valid_exact']}/{combined['span_validity']['proposed_supported']}",
        f"- Evidence-group improvements/regressions: {combined['comparison']['evidence_group_improvement_count']}/{combined['comparison']['evidence_group_regression_count']}",
        f"- Upstream exclusions: retrieval {combined['unsupported']['retrieval_bound_question_count']} questions/{combined['unsupported']['retrieval_bound_evidence_group_count']} groups; selection {combined['unsupported']['selection_bound_question_count']} questions/{combined['unsupported']['selection_bound_evidence_group_count']} groups",
        "",
        "The canonical 47/59 value is an evidence-group micro metric, not a",
        "question rate. Both units are reported separately. Gold IDs and spans",
        "were absent from model input and used only for deterministic scoring.",
        "",
    ]
    return "\n".join(lines).encode("utf-8")


def evaluate_and_freeze(
    root: Path,
    *,
    model: str = DEFAULT_MODEL,
    timeout: float = 240.0,
    evaluated_at: str | None = None,
    proposal_input: Path | None = None,
    prior_report_input: Path | None = None,
) -> dict[str, Any]:
    root = root.resolve()
    if (proposal_input is None) != (prior_report_input is None):
        raise RuntimeError("Frozen proposal rescore requires proposal and prior report")
    input_paths = {
        "enumeration": root / DEFAULT_ENUMERATION,
        "canary_32": root / DEFAULT_CANARY,
        "dev_63": root / DEFAULT_DEV,
        "reranker_results": root / DEFAULT_RERANK_RESULTS,
        "reranker_scores": root / DEFAULT_RERANK_SCORES,
        "reranker_manifest": root / DEFAULT_RERANK_MANIFEST,
        "dev_baseline_cases": root / DEFAULT_DEV_BASELINE_CASES,
        "dev_baseline_manifest": root / DEFAULT_DEV_BASELINE_MANIFEST,
        "canary_baseline_cases": root / DEFAULT_CANARY_BASELINE_CASES,
        "canary_baseline_manifest": root / DEFAULT_CANARY_BASELINE_MANIFEST,
        "chunks": root / DEFAULT_CHUNKS,
        "contract": root / DEFAULT_CONTRACT,
        "model_caller_source": root / "src/v3/evaluate_semantic_requirement_planner.py",
        "evaluator_source": Path(__file__).resolve(),
    }
    if proposal_input is not None and prior_report_input is not None:
        input_paths["frozen_proposals"] = proposal_input.resolve()
        input_paths["prior_model_run_report"] = prior_report_input.resolve()
    input_hashes = {name: file_sha256(path) for name, path in input_paths.items()}
    cases = build_cases(
        read_jsonl(input_paths["canary_32"]),
        read_jsonl(input_paths["dev_63"]),
        read_jsonl(input_paths["enumeration"]),
        read_jsonl(input_paths["reranker_results"]),
        read_jsonl(input_paths["reranker_scores"]),
        read_jsonl(input_paths["canary_baseline_cases"]),
        read_jsonl(input_paths["dev_baseline_cases"]),
        read_jsonl(input_paths["chunks"]),
    )
    if proposal_input is None:
        model_meta = runtime_metadata(model, timeout)
        proposals, call_logs = run_span_model(cases, model=model, timeout=timeout)
        latency = _latency(call_logs)
        proposal_source = "model_run"
    else:
        proposals = read_jsonl(proposal_input)
        if {row["case_id"] for row in proposals} != {
            row["case_id"] for row in cases
        }:
            raise RuntimeError("Frozen proposal IDs differ from the 95 evaluation cases")
        prior_report = json.loads(prior_report_input.read_text(encoding="utf-8"))
        model_meta = {
            key: value
            for key, value in prior_report["model"].items()
            if key not in {"prompt_sha256", "task"}
        }
        latency = prior_report["latency"]
        proposal_source = "frozen_proposal_rescore"
    assembled = cut_exact_spans(cases, proposals)
    scored = score_cases(cases, assembled)

    evidence_dir = root / "data/v3/evidence"
    reports_dir = root / "reports/v3"
    proposal_bytes = _serialize_jsonl(proposals, lambda row: row["case_id"])
    proposal_sha = _sha256_bytes(proposal_bytes)
    proposal_path = evidence_dir / f"extractive_assembler_proposals_{proposal_sha}.jsonl"
    write_immutable(proposal_path, proposal_bytes)
    assembled_bytes = _serialize_jsonl(assembled, lambda row: row["case_id"])
    assembled_sha = _sha256_bytes(assembled_bytes)
    assembled_path = evidence_dir / f"extractive_assembler_cases_{assembled_sha}.jsonl"
    write_immutable(assembled_path, assembled_bytes)
    scored_bytes = _serialize_jsonl(scored, lambda row: row["case_id"])
    scored_sha = _sha256_bytes(scored_bytes)
    scored_path = evidence_dir / f"extractive_assembler_diagnostics_{scored_sha}.jsonl"
    write_immutable(scored_path, scored_bytes)

    metrics = {
        "combined": aggregate(scored),
        "downgraded_canary_32": aggregate(
            [row for row in scored if row["dataset"] == "downgraded_canary_32"]
        ),
        "adaptive_dev_63": aggregate(
            [row for row in scored if row["dataset"] == "adaptive_dev_63"]
        ),
    }
    gate_result = gate(metrics)
    report = {
        "report_schema_version": REPORT_SCHEMA_VERSION,
        "evaluator_version": EVALUATOR_VERSION,
        "evaluated_at": evaluated_at or datetime.now(timezone.utc).isoformat(),
        "evaluation_role": "development_only_32_plus_63",
        "decision": gate_result["decision"],
        "gate": gate_result,
        "metrics": metrics,
        "latency": latency,
        "model": {
            **model_meta,
            "prompt_sha256": _prompt_sha256(),
            "task": "structured_span_location_only",
        },
        "metric_units": {
            "canonical_47_of_59": "adaptive_dev_evidence_group_micro",
            "all_groups_cited": "question_level",
            "per_requirement": "descriptive_without_requirement_to_gold_group_semantic_mapping",
        },
        "contract": {
            "selected_evidence_source": "whole_question_baseline_not_no_go_requirement_union",
            "requirement_reranker_use": "ordering_attribution_inside_frozen_selected_set_only",
            "proposal_source": proposal_source,
            "exact_substring_enforced_by": "deterministic_python_find_and_slice",
            "gold_ids_available_to_model": False,
            "gold_spans_available_to_model": False,
        },
        "scope": {
            "assembler_only": True,
            "entailment_judge": "parked",
            "answerability": "parked",
            "freeform_generation": False,
            "training": False,
            "new_keyword_rules": False,
            "retrieval_changed": False,
            "reranker_changed": False,
            "planner_changed": False,
            "new_canary": False,
            "frozen_blind_accessed": False,
            "runtime_or_canonical_promotion": False,
        },
    }
    report_bytes = _canonical_json_bytes(report)
    report_sha = _sha256_bytes(report_bytes)
    report_path = reports_dir / f"extractive_assembler_pilot_{report_sha}.json"
    write_immutable(report_path, report_bytes)
    markdown_bytes = _markdown(report)
    markdown_sha = _sha256_bytes(markdown_bytes)
    markdown_path = reports_dir / f"extractive_assembler_pilot_{markdown_sha}.md"
    write_immutable(markdown_path, markdown_bytes)

    manifest = {
        "manifest_schema_version": MANIFEST_SCHEMA_VERSION,
        "evaluator_version": EVALUATOR_VERSION,
        "source_commit": _git_head(root),
        "inputs": {
            name: {"path": _relative(root, path), "sha256": input_hashes[name]}
            for name, path in input_paths.items()
        },
        "model": report["model"],
        "artifacts": {
            "proposals": {
                "path": _relative(root, proposal_path),
                "sha256": proposal_sha,
                "row_count": len(proposals),
            },
            "assembled_cases": {
                "path": _relative(root, assembled_path),
                "sha256": assembled_sha,
                "row_count": len(assembled),
            },
            "diagnostics": {
                "path": _relative(root, scored_path),
                "sha256": scored_sha,
                "row_count": len(scored),
            },
            "report": {"path": _relative(root, report_path), "sha256": report_sha},
            "report_markdown": {
                "path": _relative(root, markdown_path),
                "sha256": markdown_sha,
            },
        },
        "decision": gate_result["decision"],
        "gold_available_to_model": False,
    }
    manifest_bytes = _canonical_json_bytes(manifest)
    manifest_sha = _sha256_bytes(manifest_bytes)
    manifest_path = evidence_dir / f"extractive_assembler_manifest_{manifest_sha}.json"
    write_immutable(manifest_path, manifest_bytes)

    for name, path in input_paths.items():
        if file_sha256(path) != input_hashes[name]:
            raise RuntimeError(f"Input changed during assembler pilot: {name}")
    return {
        "decision": gate_result["decision"],
        "gate": gate_result,
        "metrics": metrics,
        "latency": latency,
        "model": report["model"],
        "proposals": str(proposal_path),
        "proposals_sha256": proposal_sha,
        "assembled_cases": str(assembled_path),
        "assembled_cases_sha256": assembled_sha,
        "diagnostics": str(scored_path),
        "diagnostics_sha256": scored_sha,
        "report": str(report_path),
        "report_sha256": report_sha,
        "manifest": str(manifest_path),
        "manifest_sha256": manifest_sha,
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run the exact-extractive requirement answer assembler pilot"
    )
    parser.add_argument("--root", type=Path, default=Path.cwd())
    parser.add_argument("--model", default=DEFAULT_MODEL)
    parser.add_argument("--timeout", type=float, default=240.0)
    parser.add_argument("--evaluated-at")
    parser.add_argument("--reuse-proposals", type=Path)
    parser.add_argument("--reuse-report", type=Path)
    return parser.parse_args()


def main() -> None:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    args = parse_args()
    result = evaluate_and_freeze(
        args.root,
        model=args.model,
        timeout=args.timeout,
        evaluated_at=args.evaluated_at,
        proposal_input=args.reuse_proposals,
        prior_report_input=args.reuse_report,
    )
    print(json.dumps(result, ensure_ascii=False, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
